-- The part of the API's schema the worker touches (backend migrations
-- 4d0e9b1a8c6f and 5e1f0c2a9b7d). The worker does not own the schema; its
-- integration tests build this copy in their own database. Keep it in step
-- with the backend's models (tasks, celery_queue, task_events).

DROP TABLE IF EXISTS task_events, celery_queue, tasks CASCADE;
DROP FUNCTION IF EXISTS task_events_notify() CASCADE;
DROP TYPE IF EXISTS taskstatus, tasktype CASCADE;

CREATE TYPE taskstatus AS ENUM ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED');
CREATE TYPE tasktype AS ENUM ('DEPLOY', 'UPDATE', 'DESTROY', 'PAUSE', 'RESUME', 'REDEPLOY');

CREATE TABLE tasks (
    "taskId"            uuid PRIMARY KEY,
    "deploymentId"      uuid NOT NULL,
    "celeryTaskId"      varchar,
    type                tasktype NOT NULL,
    status              taskstatus,
    started_at          timestamp,
    finished_at         timestamp,
    logs                text,
    tf_state            text,
    outputs             text,
    current_phase       varchar(50),
    progress_pct        integer,
    created_at          timestamp DEFAULT timezone('UTC', now()),
    claimed_by          text,
    lease_until         timestamptz,
    cancel_requested_at timestamptz,
    finalized_at        timestamptz,
    outputs_enc         bytea
);
CREATE UNIQUE INDEX uq_tasks_active_per_deployment ON tasks ("deploymentId") WHERE status IN ('PENDING', 'RUNNING');

CREATE TABLE celery_queue (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue          text NOT NULL,
    payload        jsonb NOT NULL,
    task_id        uuid,
    after_task     uuid,
    created_at     timestamptz NOT NULL DEFAULT now(),
    visible_after  timestamptz NOT NULL DEFAULT now(),
    claimed_by     text,
    delivery_count integer NOT NULL DEFAULT 0
);
CREATE INDEX ix_celery_queue_ready ON celery_queue (queue, visible_after, id);
CREATE UNIQUE INDEX uq_celery_queue_task_id ON celery_queue (task_id) WHERE task_id IS NOT NULL;
CREATE INDEX ix_celery_queue_after_task ON celery_queue (after_task) WHERE after_task IS NOT NULL;

CREATE TABLE task_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    uuid NOT NULL REFERENCES tasks ("taskId") ON DELETE CASCADE,
    type       text NOT NULL,
    payload    jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_task_events_task ON task_events (task_id, id);

CREATE FUNCTION task_events_notify() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('task_events', NEW.task_id::text || ':' || NEW.id::text || ':' || NEW.type);
    RETURN NULL;
END
$$;
CREATE TRIGGER task_events_notify AFTER INSERT ON task_events FOR EACH ROW EXECUTE FUNCTION task_events_notify();

-- The worker's role with the grants of migration 5e1f0c2a9b7d; the tests
-- in tests/test_job_runtime.py run jobs as this role to prove the worker
-- needs no more than that.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'appstore_worker') THEN
        CREATE ROLE appstore_worker NOLOGIN;
    END IF;
END
$$;
ALTER ROLE appstore_worker LOGIN PASSWORD 'worker-test-password';
GRANT USAGE ON SCHEMA public TO appstore_worker;
GRANT SELECT, UPDATE, DELETE ON celery_queue TO appstore_worker;
GRANT INSERT ON task_events TO appstore_worker;
GRANT SELECT ("taskId", "deploymentId", type, status, claimed_by, lease_until, cancel_requested_at)
   ON tasks TO appstore_worker;
GRANT UPDATE (status, started_at, finished_at, logs, outputs_enc, current_phase, progress_pct,
              claimed_by, lease_until)
   ON tasks TO appstore_worker;
